site_name: SOSTENIBILIDAD APLICADA AL SISTEMA PRODUCTIVO
site_url: https://JoseAngelSeveroOchoa.github.io/Sostenibilidad/

theme:
  name: material
  language: es

nav:
  - Inicio: index.md
  - Presentación Módulo: SOS_Presentacion.md

markdown_extensions:
  - admonition
  - pymdownx.details     # Opcional: permite cajas desplegables (??? note)
  - pymdownx.superfences # Recomendado para compatibilidad
