site_name: SOSTENIBILIDAD
site_url: https://JoseAngelSeveroOchoa.github.io/Sostenibilidad/

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details     # Opcional: permite cajas desplegables (??? note)
  - pymdownx.superfences # Recomendado para compatibilidad
